### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by hanbim520** [albuer/heapsnap#4]
D:\share>D:\android-ndk-r13b\build\ndk-build.cmd
process_begin: CreateProcess(NULL, expr < 6.0, ...) failed.
process_begin: CreateProcess(NULL, expr < 6.0, ...) failed.
process_begin: CreateProcess(NULL, expr < 6.0, ...) failed.
process_begin: CreateProcess(NULL, expr < 6.0, ...) failed.
process_begin: CreateProcess(NULL, expr < 6.0, ...) failed.
process_begin: CreateProcess(NULL, expr < 6.0, ...) failed.
process_begin: CreateProcess(NULL, expr < 6.0, ...) failed.
[arm64-v8a] SharedLibrary  : libheapsnap.so
./obj/local/arm64-v8a/objs/heapsnap/libheapsnap/heapsnap.o: In function `heapsnap_save':
D:\share/jni/libheapsnap/heapsnap.cpp:285: undefined reference to `get_malloc_leak_info'
./obj/local/arm64-v8a/objs/heapsnap/libheapsnap/heapsnap.o: In function `dump_backtrace_symbols(__sFILE*, unsigned long*, unsigned long)':
D:\share/jni/libheapsnap/heapsnap.cpp:156: undefined reference to `__cxa_demangle'
./obj/local/arm64-v8a/objs/heapsnap/libheapsnap/heapsnap.o: In function `heapsnap_save':
D:\share/jni/libheapsnap/heapsnap.cpp:338: undefined reference to `free_malloc_leak_info'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/arm64-v8a/libheapsnap.so] Error 1

你好，感觉是不是依赖bionic库了？

**Comment by albuer** [comment]
是的，它依赖bionic库，用于取得native heap信息。
