### ISSUE TITLE
heapsnap日志没有生成

### ISSUE THREAD

**Issue by lucky-tom** [albuer/heapsnap#7]
Heap Snap Version 0.2
libc_path:libc.so
linker_path:libdl.so
Attach process<11007> at oneshot mode.
Process<11007>: mmap a buffer 1024@0xb0558000
Process<11007>: dlopen return handle 0x0 for /data/local/tmp/libheapsnap.so
Process<11007>: func [heapsnap_save] address 0x0, running...
Process<11007>: func [heapsnap_save] done.
Process<11007>: dlclose /data/local/tmp/libheapsnap.so.
Process<11007>: munmap 1024@0xb0558000.
Process<11007>: reset regs
Dettach process<11007>

这是我执行 /data/local/tmp/heapsnap -p 11007 -l /data/local/tmp/libheapsnap.so -o -f heapsnap_save  后的结果

但是没有生成任何文件

我怀疑是因为我的设备系统库中缺少libc_malloc_debug_leak.so

**Comment by albuer** [comment]
是的，heapsnap工具依赖于android的libc debug，需要libc_malloc_debug_xxxx.so
